# Generated by Django 4.2.6 on 2023-12-07 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 7, 15, 5, 13, 622466, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha publicacion",
            ),
        ),
    ]
