# Generated by Django 4.2.6 on 2023-12-17 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="get_posts", to="blog.category", verbose_name="Categorias"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 17, 20, 6, 12, 222631, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha publicacion",
            ),
        ),
    ]
